# Version: 1.0
FROM golang:1.13.1-alpine as builder

RUN echo "https://mirrors.aliyun.com/alpine/v3.10/main" > /etc/apk/repositories && \
  apk add --update --no-cache git && \
  rm -rf /var/cache/apk/*

RUN mkdir -p /data/app /go/src/github.com/RivenZoo/backbone
ADD ./ /data/app
ADD ./logger /go/src/github.com/RivenZoo/backbone
RUN cd /data/app/cmd/projcreator && go build .

FROM alpine:3.7

RUN mkdir -p /data/app

WORKDIR /data/app

COPY --from=builder /data/app/cmd/projcreator /usr/local/bin

